// APCA targets below are design checks, not WCAG conformance ratings.
import { calcAPCA } from "apca-w3";
import { converter, formatHex, toGamut } from "culori";
import { readFile, writeFile } from "node:fs/promises";

const toOklch = converter("oklch");
const rgbGamut = toGamut("rgb");
const seeds = { neutral: "#6d7c72", green: "#769b6a", red: "#c36761", amber: "#b58b43" };

function tone(seed, lightness) {
  const base = toOklch(seed);
  const shift = (lightness - base.l) * 6 * Math.sin(((base.h - 105) * Math.PI) / 90);
  return formatHex(
    rgbGamut({
      mode: "oklch",
      l: lightness,
      c: base.c <= 0.0001 ? 0 : base.c * Math.pow(Math.sin(Math.PI * lightness), 0.75),
      h: base.h === undefined ? undefined : (base.h + shift + 360) % 360,
    }),
  );
}

function contrast(text, background) {
  return Math.abs(Number(calcAPCA(text, background)));
}

// Solve against the actual painted background, including dark surfaces.
function readable(seed, background, target, lightText) {
  const backgroundL = toOklch(background).l;
  let low = lightText ? backgroundL : 0;
  let high = lightText ? 1 : backgroundL;
  let result = tone(seed, lightText ? 1 : 0);
  for (let index = 0; index < 24; index++) {
    const mid = (low + high) / 2;
    const candidate = tone(seed, mid);
    const meets = contrast(candidate, background) >= target;
    if (meets) result = candidate;
    if (lightText === meets) high = mid;
    else low = mid;
  }
  if (contrast(result, background) < target)
    throw new Error(`Unreachable APCA target ${target}: ${seed} on ${background}`);
  return result;
}

const checks = [];
function palette(dark) {
  const neutral = (light, dim) => tone(seeds.neutral, dark ? dim : light);
  const surface = neutral(0.996, 0.235);
  const hover = neutral(0.93, 0.33);
  const accent = tone(seeds.green, dark ? 0.32 : 0.93);
  const dangerSurface = tone(seeds.red, dark ? 0.3 : 0.94);
  const warningSurface = tone(seeds.amber, dark ? 0.31 : 0.94);
  const fill = readable(seeds.green, hover, 80, dark);
  const colors = {
    background: neutral(0.977, 0.19),
    surface,
    sidebar: neutral(0.955, 0.215),
    "control-surface": neutral(0.992, 0.28),
    "input-surface": neutral(0.999, 0.205),
    "control-hover": hover,
    text: readable(seeds.neutral, hover, 90, dark),
    muted: readable(seeds.neutral, hover, 75, dark),
    border: neutral(0.83, 0.43),
    "border-strong": neutral(0.64, 0.58),
    accent,
    "accent-text": readable(seeds.green, accent, 80, dark),
    focus: fill,
    fill,
    "fill-hover": tone(seeds.green, toOklch(fill).l + (dark ? 0.025 : -0.025)),
    "on-fill": readable(seeds.neutral, fill, 75, !dark),
    success: readable(seeds.green, accent, 80, dark),
    danger: readable(seeds.red, dangerSurface, 80, dark),
    warning: readable(seeds.amber, warningSurface, 80, dark),
    "success-surface": accent,
    "danger-surface": dangerSurface,
    "warning-surface": warningSurface,
    "checked-text": readable(seeds.neutral, fill, 75, !dark),
    "switch-track": neutral(0.75, 0.43),
    "switch-thumb": neutral(1, 0.97),
  };
  for (const [foreground, background, target] of [
    ["text", "background", 90],
    ["text", "surface", 90],
    ["text", "control-hover", 90],
    ["muted", "background", 75],
    ["muted", "surface", 75],
    ["muted", "control-hover", 75],
    ["accent-text", "accent", 75],
    ["success", "success-surface", 75],
    ["danger", "danger-surface", 75],
    ["warning", "warning-surface", 75],
    ["on-fill", "fill", 75],
    ["on-fill", "fill-hover", 75],
  ]) {
    const score = contrast(colors[foreground], colors[background]);
    if (score < target)
      throw new Error(
        `${dark ? "dark" : "light"} ${foreground}/${background}: ${score} < ${target}`,
      );
    checks.push({
      theme: dark ? "dark" : "light",
      foreground,
      background,
      score: Number(score.toFixed(1)),
    });
  }
  return colors;
}

const css =
  [
    "/* Generated by scripts/generate-palette.mjs; edit the seed colors there. */",
    ...[false, true].map((dark) => {
      const lines = Object.entries(palette(dark)).map(
        ([name, value]) => `  --cc-${name}: ${value};`,
      );
      return `${dark ? ':root[data-cc-theme="dark"]' : ":root"} {\n  color-scheme: ${dark ? "dark" : "light"};\n${lines.join("\n")}\n}`;
    }),
  ].join("\n") + "\n";
const output = new URL("../packages/ui/palette.css", import.meta.url);
if (process.argv.includes("--check")) {
  if ((await readFile(output, "utf8")) !== css)
    throw new Error("Palette is stale; run vp run theme:generate");
} else {
  await writeFile(output, css);
}
console.log(
  `${checks.length} APCA color pairs verified; lowest text Lc ${Math.min(...checks.map((check) => check.score))}`,
);
console.table(checks);
