name: Static checks
on:
  workflow_call:
    inputs:
      rust:
        type: boolean
        default: false
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CHORD_CONTROL_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: voidzero-dev/setup-vp@v1.20.0
        with:
          node-version-file: .node-version
          cache: true
          run-install: false
      - run: vp install --frozen-lockfile --ignore-scripts
      - run: vp check
      - run: vp run check:svelte
      - run: vp run knip
      - uses: dtolnay/rust-toolchain@stable
        if: inputs.rust
        with:
          components: rustfmt
      - run: vp run format:rust:check
        if: inputs.rust
